---

- name: Print Bootloader Disks to Build
  ansible.builtin.debug:
    var: bootloader_disks

- name: Generate menus
  ansible.builtin.include_tasks: generate_menus.yml
  when:
    - generate_menus | default(true) | bool

- name: Generate iPXE bootloaders
  ansible.builtin.include_tasks: generate_disks.yml
  with_items:
    - "{{ bootloader_disks }}"
  loop_control:
    loop_var: bootloader_file
  when:
    - generate_disks | default(true) | bool
