---
apiVersion: v1
kind: Pod
metadata:
  name: uponlan
spec:
  containers:
    - name: webapp
      image: localhost/uponlan:latest
      env:
        - name: MENU_VERSION
          value: "0.0.2"
        - name: ENDPOINT_URL
          value: "https://github.com/mozebaltyk/uponlan"
        - name: NGINX_PORT
          value: "8080"
        - name: WEB_APP_PORT
          value: "3000"
        - name: TFTPD_OPTS
          value: "--tftp-single-port"
      volumeMounts:
        - name: uponlan-config
          mountPath: /config
        - name: uponlan-assets
          mountPath: /assets
        - name: uponlan-menu
          mountPath: /menu
        - name: uponlan-logs
          mountPath: /logs
      ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 3000
          hostPort: 3000
        - containerPort: 69
          protocol: UDP
          hostPort: 69
  volumes:
    - name: uponlan-config
      emptyDir:
        path: ./config
    - name: uponlan-assets
      emptyDir:
        path: ./assets
    - name: uponlan-menu
      emptyDir:
        path: ./menu
    - name: uponlan-logs
      emptyDir:
        path: ./logs
