ipxe_branch: master
ipxe_ca_filename: ca-ipxe-org.crt
ipxe_ca_url: http://ca.ipxe.org/ca.crt
ipxe_debug_enabled: false
ipxe_debug_options: httpcore,tls
ipxe_repo: https://github.com/ipxe/ipxe
ipxe_source_dir: /usr/src/ipxe
kernel_params: initrd=initrd.magic ${cmdline}
live_endpoint: https://github.com/netbootxyz
make_num_jobs: 1
memdisk_location: http://${boot_domain}/memdisk
netbootxyz_conf_dir: /etc/netbootxyz
netbootxyz_root: /var/www/html
pciids_url: https://raw.githubusercontent.com/netbootxyz/pciids/master/pciids.ipxe
pipxe_branch: master
pipxe_repo: https://github.com/netbootxyz/pipxe
pipxe_source_dir: /usr/src/pipxe