#!/bin/bash
set -e

if [[ $# -ne 1 ]]; then 
echo "Usage: $0 <hard_release_version>"
exit 1; 
fi

HARD_RELEASE=$1

# The release tarball must contain the iPXE artifacts the libvirt network
# advertises (rom/ipxe/uponlan.xyz-*). They are generated by
# scripts/build_ipxe_roms.sh - fail immediately instead of shipping a menu
# release whose network boot answers point at files that do not exist.
REQUIRED_ROM_ARTIFACTS=(
  rom/ipxe/uponlan.xyz-undionly.kpxe   # firmware PXE stage-1 (BIOS)
  rom/ipxe/uponlan.xyz.kpxe            # iPXE stage-2 (BIOS, dhcp-boot)
  rom/ipxe/uponlan.xyz.efi             # UEFI network boot
  rom/ipxe/uponlan.xyz-e1000.rom       # built e1000 option ROM (host install)
)
missing=0
for rel in "${REQUIRED_ROM_ARTIFACTS[@]}"; do
  if [[ ! -s "./release/menus/$rel" ]]; then
    echo "ERROR: required iPXE artifact missing: release/menus/$rel" >&2
    missing=1
  fi
done
if [[ $missing -ne 0 ]]; then
  echo "ERROR: run scripts/build_ipxe_roms.sh BEFORE release_menu.sh to generate the ROM artifacts." >&2
  echo "       release_menu.sh will not proceed without them." >&2
  exit 1
fi

echo -e "\n### Releasing menu version ${HARD_RELEASE} ###\n"
release_dir="./release/output/releases/download/${HARD_RELEASE}"
mkdir -p "$release_dir"

# Set Version
sed -i -e "s/set menu_version .*$/set menu_version ${HARD_RELEASE}/" ./release/menus/version.ipxe

# ipxe Artefacts
mv ./release/menus/ipxe/* "$release_dir"/ 2> /dev/null || true

# tar all Menus Artefacts. local-vars.ipxe is a per-deployment override (local
# mirror endpoint) and must never be baked into a shipped release.
tar -czf "$release_dir/menus.tar.gz" -C ./release/menus --exclude=local-vars.ipxe .

# GitHub-like releases/latest response so the webapp's local endpoint browser
# (Menu From Endpoint URL) and dashboard resolve this version like a GitHub API.
echo "{\"tag_name\":\"${HARD_RELEASE}\"}" > ./release/output/releases/latest
