FROM ubuntu:22.04 as builder
RUN apt update && apt install -y isolinux
# Copy isolinux to later stage

FROM alpine:3.21.3

# Install development tools
RUN apk add --no-cache \
  alpine-sdk \
  python3 \
  py3-pip \
  ansible-core \
  curl wget git \
  binutils \
  dosfstools \
  gcc \
  build-base \
  syslinux \
  mtools \
  xorriso \
  xz \
  util-linux \
  libuuid \
  perl \
  xz-dev

# Copy isolinux to later stage
COPY --from=builder /usr/lib/ISOLINUX /usr/lib/ISOLINUX

# Default workdir
WORKDIR /ansible

# nbxyz
RUN adduser -u 911 -D -s /bin/sh -G users -h /ansible nbxyz
RUN addgroup -g 1001 nbxyz

# Default command
CMD ["sleep", "infinity"]
