---
## Common iPXE part
- name: Create iPXE file directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ uponlanxyz_root }}/ipxe"
    - "{{ cert_dir }}"

- name: Copy helper apps
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ uponlanxyz_root }}"
  with_items:
    - memdisk

- name: Check out latest iPXE sources
  ansible.builtin.git:
    repo: "{{ ipxe_repo }}"
    dest: "{{ ipxe_source_dir }}"
    version: "{{ ipxe_branch }}"
    force: true
  register: ipxe_git_checkout

- name: Touch iPXE config local files
  ansible.builtin.file:
    path: "{{ ipxe_source_dir }}/{{ item }}"
    state: touch
  with_items:
    - src/config/local/umalloc.h
    - src/config/local/nap.h
    - src/config/local/timer.h
    - src/config/local/branding.h
    - src/config/local/serial.h
    - src/config/local/reboot.h
    - src/config/local/sanboot.h
    - src/config/local/fault.h
    - src/config/local/dhcp.h
    - src/config/local/sideband.h
    - src/config/local/entropy.h
    - src/config/local/crypto.h
    - src/config/local/usb.h
    - src/config/local/settings.h
    - src/config/local/isa.h

- name: Retrieve iPXE CA
  ansible.builtin.get_url:
    url: "{{ ipxe_ca_url }}"
    dest: "{{ cert_dir }}/{{ ipxe_ca_filename }}"

## Bootloader part
- name: Set var to bootloader filename of loop
  ansible.builtin.set_fact:
    bootloader_filename: "{{ bootloader_file.filename }}"

- name: Set var to bootloader type of loop
  ansible.builtin.set_fact:
    bootloader_template: "{{ bootloader_file.template }}"

- name: Debug filename
  ansible.builtin.debug:
    var: bootloader_filename

- name: Debug type
  ansible.builtin.debug:
    var: bootloader_template

- name: Copy iPXE Bootloader template to iPXE source directory
  ansible.builtin.template:
    src: "disks/{{ bootloader_template }}.j2"
    dest: "{{ ipxe_source_dir }}/src/{{ bootloader_filename }}"
