---

- name: Find files under /config/menus/
  ansible.builtin.find:
    paths: /config/menus/
    file_type: file
  register: found_files

- name: Copy source files from webapp to uponlanxyz_root
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ uponlanxyz_root }}/{{ item.path | regex_replace('^/config/menus/', '') }}"
  loop: "{{ found_files.files }}"

  ## PCIids part
- name: Retrieve pciids.ipxe
  ansible.builtin.get_url:
    url: "{{ pciids_url }}"
    dest: "{{ uponlanxyz_root }}/pciids.ipxe"
